import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import './styles.css';
import './markdown.css';
import type { LabSession, ChatMessage, ResearchMode, Telemetry } from '../../shared/types';

const api = async (path:string, options?:RequestInit) => { const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options}); const j=await r.json(); if(!r.ok) throw new Error(j.error||'Request failed'); return j; };
const timeLeft=(ends?:string) => { if(!ends)return '--:--'; const n=Math.max(0,new Date(ends).getTime()-Date.now()); return `${String(Math.floor(n/60000)).padStart(2,'0')}:${String(Math.floor(n/1000)%60).padStart(2,'0')}`; };
function MarkdownContent({ content }: { content: string }) {
 const [copied, setCopied] = useState<string | null>(null);
 const copy = async (value: string) => { await navigator.clipboard?.writeText(value); setCopied(value); window.setTimeout(() => setCopied(null), 1400); };
 return <ReactMarkdown remarkPlugins={[remarkGfm]} components={{
   a: ({ children, href }) => <a href={href} target="_blank" rel="noreferrer">{children}</a>,
   code: ({ className, children, ...props }) => {
     const value = String(children).replace(/\n$/, '');
     const inline = !className;
     if (inline) return <code {...props}>{children}</code>;
     const language = className?.replace('language-', '') || 'code';
     return <div className="code-block"><div className="code-head"><span>{language}</span><button onClick={() => copy(value)}>{copied === value ? 'Copied' : 'Copy'}</button></div><pre><code className={className}>{value}</code></pre></div>;
   }
 }}>{content}</ReactMarkdown>;
}
function App(){
 const [conversations,setConversations]=useState<any[]>([]),[selected,setSelected]=useState('sample-conversation'),[messages,setMessages]=useState<ChatMessage[]>([]),[input,setInput]=useState(''),[mode,setMode]=useState<ResearchMode>('normal'),[lab,setLab]=useState<LabSession|null>(null),[telemetry,setTelemetry]=useState<Telemetry|null>(null),[busy,setBusy]=useState(false),[remaining,setRemaining]=useState('--:--'),[toast,setToast]=useState('');
 const [showNew,setShowNew]=useState(false);
 useEffect(()=>{api('/api/conversations').then(setConversations).catch(e=>setToast(e.message)); const es=new EventSource('/api/events'); es.addEventListener('lab',e=>{const s=JSON.parse((e as MessageEvent).data);setLab(s);}); es.addEventListener('telemetry',e=>setTelemetry(JSON.parse((e as MessageEvent).data))); return()=>es.close();},[]);
 useEffect(()=>{api(`/api/conversations/${selected}`).then(j=>{setMessages(j.messages);setMode(j.conversation.mode)}).catch(()=>{});},[selected]);
 useEffect(()=>{const i=setInterval(()=>setRemaining(timeLeft(lab?.endsAt)),1000);return()=>clearInterval(i)},[lab?.endsAt]);
 const send=async()=>{if(!input.trim()||busy)return;setBusy(true);const content=input;setInput('');try{const r=await api(`/api/conversations/${selected}/messages`,{method:'POST',body:JSON.stringify({content,mode})});setMessages(m=>[...m,r.user,r.assistant]);}catch(e){setToast((e as Error).message)}finally{setBusy(false)}};
 const createConversation=async()=>{const c=await api('/api/conversations',{method:'POST',body:JSON.stringify({title:'New research thread',mode})});setConversations(c=>[c,...c]);setSelected(c.id);setShowNew(false)};
 const createLab=async()=>{try{const s=await api('/api/lab/sessions',{method:'POST',body:JSON.stringify({name:'Detonation Lab / Sample 01',template:'Win11-Defender-Baseline',durationMinutes:30,networkMode:'isolated',telemetry:true,autoRevert:true})});setLab(s);setToast('Isolated mock lab provisioned')}catch(e){setToast((e as Error).message)}};
 const labAction=async(action:string)=>{if(!lab)return;try{const r=await api(`/api/lab/sessions/${lab.id}/${action}`,{method:'POST',body:JSON.stringify(action==='extend'?{minutes:15}:{})});if(action==='telemetry')setTelemetry(r);else setLab(r);}catch(e){setToast((e as Error).message)}};
 return <div className="app"><aside className="sidebar"><div className="brand"><span className="brand-mark">⌁</span><div><strong>CYBERLAB</strong><small>AI RESEARCH CONSOLE</small></div></div><button className="new-btn" onClick={()=>setShowNew(true)}>＋ New research thread</button><div className="side-label">CONVERSATIONS <span>{conversations.length}</span></div><div className="threads">{conversations.map(c=><button className={`thread ${c.id===selected?'active':''}`} onClick={()=>setSelected(c.id)} key={c.id}><i className={c.mode==='lab'?'orange':''}></i><span>{c.title}</span><em>{c.mode==='lab'?'LAB':'CHAT'}</em></button>)}</div><div className="sidebar-foot"><div className="secure"><span>●</span> LOCAL SECURE ENVIRONMENT</div><div className="user"><div className="avatar">AR</div><div><strong>Authorized researcher</strong><small>Session protected</small></div><b>···</b></div></div></aside>
 <main><header><div><span className="eyebrow">RESEARCH WORKSPACE / 01</span><h1>{mode==='lab'?'Controlled experiment':'Defensive research'}</h1></div><div className="header-tools"><button className={`mode ${mode}`} onClick={()=>setMode(mode==='normal'?'lab':'normal')}><span></span>{mode==='normal'?'NORMAL MODE':'RESEARCH LAB MODE'}⌄</button><div className="model"><span className="pulse"></span><div><b>Gemini 3.5 Flash Lite</b><small>Provider connected · server-side</small></div></div></div></header>
 <div className="workspace"><section className="chat"><div className="chat-scroll">{messages.length===0&&<div className="empty"><div className="radar">◉</div><h2>Start a secure research thread</h2><p>Ask about telemetry, detection engineering, incident response, or create an isolated lab session.</p><div className="prompts"><button onClick={()=>setInput('Interpret these process events and identify defensive next steps.')}>Interpret telemetry</button><button onClick={()=>setInput('Draft a Sigma rule for suspicious PowerShell child processes.')}>Draft a Sigma rule</button></div></div>}{messages.map(m=><div className={`message ${m.role}`} key={m.id}><div className="msg-avatar">{m.role==='assistant'?'⌁':'AR'}</div><div><div className="msg-meta">{m.role==='assistant'?'CYBERLAB AI':'AUTHORIZED RESEARCHER'} <span>{new Date(m.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span></div><div className="bubble"><MarkdownContent content={m.content}/></div></div></div>)}{busy&&<div className="message assistant"><div className="msg-avatar">⌁</div><div><div className="msg-meta">CYBERLAB AI</div><div className="bubble typing"><i></i><i></i><i></i></div></div></div>}</div><div className="composer"><div className="composer-mode">{mode==='lab'?'⌁ LAB CONTEXT ENABLED':'◈ DEFENSIVE CONTEXT'} <span>·</span> sandbox boundaries enforced</div><div className="input-row"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Ask CyberLab AI about your research..."/><button onClick={send} disabled={busy}>↑</button></div><div className="composer-foot"><span>Enter to send · Shift + Enter for new line</span><span className="lock">▣ API key never exposed to browser</span></div></div></section>
 <aside className="rightbar"><div className="panel-head"><span>LAB SESSION</span><b className="live"><i></i>{lab?.state?.toUpperCase()||'STANDBY'}</b></div>{lab?<><div className="lab-title"><div className="vm-icon">▣</div><div><strong>{lab.name}</strong><small>{lab.template}</small></div></div><div className="timer"><small>TIME REMAINING</small><strong>{remaining}</strong><span>session {lab.id}</span></div><div className="lab-grid"><div><small>NETWORK</small><b>{lab.networkMode.toUpperCase()}</b></div><div><small>TELEMETRY</small><b className="green">{lab.telemetryStatus.toUpperCase()}</b></div></div><div className="actions"><button onClick={()=>labAction(lab.state==='running'?'stop':'start')}>{lab.state==='running'?'Stop session':'Start VM session'}</button><button onClick={()=>labAction('telemetry')} disabled={lab.state!=='running'}>Collect telemetry</button><button onClick={()=>labAction('extend')}>Extend +15 min</button><button onClick={()=>labAction('revert')}>Revert snapshot</button></div></>:<div className="standby"><div className="vm-outline">▣</div><strong>No active lab session</strong><p>Provision a disposable mock VM to simulate the complete malware-analysis workflow.</p><button onClick={createLab}>＋ Create isolated lab</button></div>}<div className="telemetry"><div className="panel-head"><span>ACTIVITY / TELEMETRY</span><small>LIVE FEED</small></div>{telemetry?<><div className="telemetry-row"><b>PROCESS</b><span>{telemetry.processEvents.length} events</span></div><div className="telemetry-row"><b>FILESYSTEM</b><span>{telemetry.filesystemEvents.length} events</span></div><div className="telemetry-row"><b>NETWORK</b><span>{telemetry.networkEvents.length} events</span></div><div className="event-log">{telemetry.processEvents.map((e,i)=><div key={i}><i></i><span>{e.process} <small>{e.action}</small></span><time>now</time></div>)}</div></>:<div className="no-data">Telemetry events will appear here when a running experiment is collected.</div>}</div></aside></div></main>{toast&&<button className="toast" onClick={()=>setToast('')}>{toast} ×</button>}{showNew&&<div className="modal"><div className="modal-box"><h2>New research thread</h2><p>Choose a conversation context for your next investigation.</p><div className="choice-row"><button className={mode==='normal'?'chosen':''} onClick={()=>setMode('normal')}>◈ Normal mode<small>Defensive analysis & education</small></button><button className={mode==='lab'?'chosen':''} onClick={()=>setMode('lab')}>⌁ Research lab<small>Authorized isolated experiments</small></button></div><div className="modal-actions"><button onClick={()=>setShowNew(false)}>Cancel</button><button className="primary" onClick={createConversation}>Create thread</button></div></div></div>}</div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
